---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Testing ibridges role
      ansible.builtin.include_role:
        name: ibridges
      vars:
        ibridges_plugins:
          - flask # fake plugin -- just a random additioanl package to install into the venv
