---
driver:
  name: ${DRIVER-podman}
provisioner:
  name: ansible
  playbooks:
    prepare: ./prepare.yml
    verify: ../default/verify.yml
    converge: ./converge.yml
  env:
    ANSIBLE_ROLES_PATH: ../../../
role_name_check: 1
platforms:
  - name: workspace-src-ubuntu_noble-nginx
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_noble-nginx
    command: /sbin/init
    published_ports:
      - 8080:80
    pre_build_image: true
    registry:
      url: ${DOCKER_REGISTRY-""}
      credentials:
        username: ${DOCKER_USER-""}
        password: ${DOCKER_PW-""}
