---
- name: Add reverse proxy template
  ansible.builtin.template:
    src: templates/reverseproxy.conf.j2
    dest: "{{ nginx_location_app_config_path }}/{{ item.name }}.conf"
    mode: "0640"
    owner: root
    group: www-data
  with_items: "{{ nginx_location_locations }}"

  # it appears community.general.htpasswd looks for passlib globally instead of in the venv in which Ansible is currently running
- name: Install dependency for htpasswd module (globally)
  ansible.builtin.package:
    name: python3-passlib

- name: Create htpasswd location
  ansible.builtin.file:
    path: "{{ nginx_location_htpasswd_path }}"
    owner: root
    group: www-data
    state: directory
    mode: "750"

- name: Create htpasswd files based on nginx_location_auth_info
  with_items: "{{ nginx_location_auth_info | default([]) }}"
  when: item.name is defined
  no_log: "{{ not nginx_location_debug }}"
  community.general.htpasswd:
    path: "{{ nginx_location_htpasswd_path }}/{{ item.name }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    mode: "644"

- name: Create htpasswd files with default username and password for all locations not defined in nginx_location_auth_info
  with_items: "{{ nginx_location_locations }}"
  when:
    - (item.auth | default('')) == 'basic'
    - (item.htpasswd | default(item.name)) not in (nginx_location_auth_info | map(attribute='name') | list)
  no_log: "{{ not nginx_location_debug }}"
  community.general.htpasswd:
    path: "{{ nginx_location_htpasswd_path }}/{{ item.htpasswd | default(item.name) }}"
    name: "{{ nginx_location_default_username }}"
    password: "{{ nginx_location_default_password }}"
    owner: root
    group: www-data
    mode: "644"

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  tags: molecule-idempotence-notest
