# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/.github/workflows/requirements.txt"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/molecule/ext/molecule-src/requirements.txt"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/playbooks/roles/asreview_server/files"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "asreview"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: "pip"
    directory: "/playbooks/roles/jupyterhub/files"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jupyterhub"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
