# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/playbooks/roles/asreview_server/files" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "asreview"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/playbooks/roles/jupyterhub/files" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jupyterhub"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
