---
platforms:
  - name: workspace-src-ubuntu_noble-desktop
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_noble-desktop
    command: /sbin/init
    pre_build_image: true
    registry:
      url: ${DOCKER_REGISTRY-""}
      credentials:
        username: ${DOCKER_USER-""}
        password: ${DOCKER_PW-""}
