---
- name: Set OS version as int
  ansible.builtin.set_fact:
    stata18_os_version: "{{ ansible_distribution_major_version | int }}"

- name: Install curses libraries to support commandline invocation of Stata
  when: (ansible_distribution == "Ubuntu" and stata18_os_version < 24) or (ansible_distribution == "Debian" and stata18_os_version <= 12)
  ansible.builtin.package:
    name: libncurses5
    state: present

- name: Install curses libraries to support commandline invocation of Stata
  when: (ansible_distribution == "Ubuntu" and stata18_os_version >= 24) or (ansible_distribution == "Debian" and stata18_os_version > 12)
  ansible.builtin.package:
    name: libncurses6
    state: present
