---
- name: Install iBridges GUI
  when: fact_desktop_workspace
  ansible.builtin.include_tasks: gui.yml

- name: Install iBridges GUI to systemwide location
  when: fact_desktop_workspace
  ansible.builtin.include_role:
    name: uv_tool
  vars:
    uv_tool_package: ibridges
    uv_tool_python: "{{ ibridges_python_path | default('/usr/bin/python3') }}"
    uv_tool_extra_packages: "{{ ibridges_install_plugins + ibridges_install_plugins_gui }}"

- name: Install iBridges CLI to systemwide location
  when: not fact_desktop_workspace
  ansible.builtin.include_role:
    name: uv_tool
  vars:
    uv_tool_package: ibridges
    uv_tool_python: "{{ ibridges_python_path | default('/usr/bin/python3') }}"
    uv_tool_extra_packages: "{{ ibridges_install_plugins }}"
