---
name: Ansible Lint
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    env:
      VIRTUAL_ENV: ${{ github.workspace }}/.venv
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Set up UV and caching
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true

      - uses: actions/checkout@v7
      - name: Install Dependencies
        run: |
          uv venv $VIRTUAL_ENV
          uv pip install ansible-lint

      - name: Run Ansible Lint
        run: |
          uv run ansible-lint .
