---
- name: Prepare
  hosts: all
  gather_facts: false

- name: Import playbook # install JupyterHub before we test this scenario
  ansible.builtin.import_playbook: "../../playbooks/jupyterhub.yml"
  vars:
    jupyterhub_debug: true
    jupyterhub_auth: noauth
    jupyterhub_activate_remote_user_auth: true
    jupyterhub_proxy_config: "{ proxy_set_header: { REMOTE_USER: '$http_user'} }"
