#!/bin/bash
#
echo "Adding asreview command function that launches virtualenv"
#
cat >> ~/.bashrc <<'INPUTEND'
# added by runonce as asreview config
asreview() {
    if [[ $@ == "lab" ]]; then
        command source /opt/venvs/asreview/bin/activate
        command asreview lab >> ~/asreview.log 2>&1
    fi
}
INPUTEND
