---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test Open VSCode
      ansible.builtin.uri:
        url: http://localhost/hub/spawn/testuser?next=%2Fhub%2Fuser%2Ftestuser%2Fopenvscode%2F
        method: GET
        headers:
          user: testuser # mock SRAM login
        return_content: true
        follow_redirects: true
      register: openvscode_login
      failed_when: openvscode_login.failed or not openvscode_login.url is match('http://localhost/user/testuser/openvscode')
      retries: 5
      delay: 3

    - name: Assert content correct
      ansible.builtin.assert:
        that:
          - '"vscode-workbench" in openvscode_login.content'

    - name: Fail if any venv file is group-writeable
      ansible.builtin.command: >
        find /usr/local/jupyterhub -type f -perm -g+w -print
      register: venv_gw_files
      changed_when: false
      failed_when: venv_gw_files.stdout != ""
