---
# sets variable {{fact_regular_users}} to a list of users
# example content with just one user named "foo":
# [   { user: "foo",
#       userid: "1000",
#       groupid: "1000",
#       home: "/home/foo",
#       shell: "/bin/bash",
#       description: "sample user foo"
#     }
# ]
#
# assumes a Unix-like environment where all users are listed in /etc/passwd
# selects users that meet the following criteria
#   - userid > 999 <= 60000  which excludes system roles
#   - home directory underneath /home
#

- name: Gather minimal system facts
  ansible.builtin.setup:
    gather_subset:
      - min
  when: ansible_os_family is not defined

- name: Populate the getent cache for all passwd entries
  ansible.builtin.getent:
    database: passwd
    split: ':'

- name: Build a list of human users
  ansible.builtin.set_fact:
    fact_regular_users: "{{ (fact_regular_users | default([])) + [dict(keys | zip([item.key, item.value[1:]] | flatten))] }}"
  loop: "{{ values }}"
  vars:
    keys:
      - user
      - userid
      - groupid
      - description
      - home
      - shell
    values: |
      {{
        getent_passwd
        | dict2items
        | selectattr('value.1', 'defined')
        | selectattr('value.1', 'ge', 1000 | string)
        | selectattr('value.1', 'le', 60000 | string)
        | selectattr('value.4', 'defined')
        | selectattr('value.4', 'match', '^/home/')
        | rejectattr('key', 'eq', 'ubuntu')
        | list
      }}

- name: Read database /etc/group
  ansible.builtin.getent:
    database: group

- name: Get CO groupnames
  ansible.builtin.slurp:
    src: /etc/rsc/managedgroups
  register: _co_groupnames

- name: Parse CO groupnames
  ansible.builtin.set_fact:
    _co_groupnames_parsed: "{{ (_co_groupnames['content'] | b64decode).split('\n') | select | list }}"

- name: Set fact CO groups
  ansible.builtin.set_fact:
    fact_co_groups: "{{ fact_co_groups | default({}) | combine({item.key: item.value[-1].split(',')}) }}"
  loop: "{{ getent_group | dict2items | selectattr('key', 'in', _co_groupnames_parsed) | list }}"
