---
name: Molecule Run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ github.actor }}
      DOCKER_PW: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_REGISTRY: ghcr.io
      ANSIBLE_FORCE_COLOR: '1'
      ANSIBLE_RESULT_FORMAT: yaml
      MOLECULE_CONFIG: molecule/ext/molecule-src/molecule.yml
      REQUIREMENTS_FILE: requirements.txt
      PLAYBOOK_DIR: ../../../ # relative to molecule/ext/molecule-src/molecule.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: git clone https://github.com/UtrechtUniversity/SRC-molecule-test.git molecule
      - run: mkdir molecule/ext && cd molecule/ext && ln -s ../../ molecule-src
      - run: pip install -r ${{ env.REQUIREMENTS_FILE }}
      - run: ansible-galaxy install -r requirements.yml
      - name: Molecule tests
        run: |
          molecule -vv -c ${{ env.MOLECULE_CONFIG }} test
