---
driver:
  name: ${DRIVER-podman}

platforms:
  - name: workspace-src-ubuntu_noble-desktop
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_noble-desktop
    pre_build_image: true
    registry:
      url: ${DOCKER_REGISTRY-""}
      credentials:
        username: ${DOCKER_USER-""}
        password: ${DOCKER_PW-""}
role_name_check: 1
provisioner:
  name: ansible
  playbooks:
    converge: ./converge.yml
  env:
    ANSIBLE_ROLES_PATH: ../../../
