- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test login
      ansible.builtin.uri:
        url: http://localhost:8000
        method: GET
        headers:
          REMOTE_USER: testuser
        return_content: true
      register: jupyterhub_login
