#!/bin/bash install python module miniconda
#
echo "Installing Anaconda"
curl https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh --output /tmp/anaconda.sh
sha256sum /tmp/anaconda.sh

bash /tmp/anaconda.sh -y
rm /tmp/anaconda.sh
source ~/.bashrc

