---
- name: Check for presence of SRC Nginx
  tags: molecule-idempotence-notest
  block:
    - name: Check for presence of SRC Nginx SRAM authentication config
      ansible.builtin.lineinfile:
        line: "{{ item }}"
        dest: /etc/nginx/app-location-conf.d/authentication.conf
      check_mode: true
      register: src_nginx_config
      with_items:
        - location @custom_401 {
        - location = /oauth2_callback {
        - location = /validate {

    - name: Ensure nginx is running #
      ansible.builtin.systemd:
        name: nginx
        state: started

    - name: Stop if SRC nginx config is not present
      ansible.builtin.fail:
        msg: SRC-Nginx is not installed or active. SRC-Nginx component must be run before this component.
      when: src_nginx_config.changed or nginx_check.stdout != 'active'
