---
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence # too many tasks are not idempotent
    - side_effect
    - verify
    - cleanup
    - destroy
