---
- name: Install iRODS server (provider role) in researchcloud workspace
  hosts: localhost
  gather_facts: true

  # irods server will use a local postgresql database

  roles:
    - role: irods_server
      vars:
        irods_server_host: "{{ workspace_fqdn | default(ansible_fqdn) }}"
