---
name: Check Markdown links

on:
  push:
    paths:
      - '**.md'

jobs:
  build:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    env:
      VIRTUAL_ENV: ${{ github.workspace }}/.venv
      CHECK_FILES: docs/ CONTRIBUTING.md TESTING.md README.md
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Set up UV and caching
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          enable-cache: true

      - uses: actions/checkout@v7
      - name: Install Dependencies
        run: |
          uv venv $VIRTUAL_ENV
          uv pip install markdown-checker

      - name: Run markdown-checker
        run: |
          uv run markdown-checker ${{ env.CHECK_FILES }} -f check_broken_urls -f check_broken_paths
