---
name: Biweekly molecule run for playbooks
on:
  schedule:
    - cron: '22 2 * * 3'  # 2:22am on Monday
  workflow_dispatch:

env:
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PW: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REGISTRY: ghcr.io
  ANSIBLE_FORCE_COLOR: '1'
  ANSIBLE_CALLBACK_RESULT_FORMAT: yaml
  MOLECULE_CONFIG: molecule/ext/molecule-src/molecule.yml
  REQUIREMENTS_FILE: molecule/ext/molecule-src/requirements.txt
  ANSIBLE_REQUIREMENTS_FILE: molecule/ext/molecule-src/requirements.yml
  CRUN_VER: 1.11.2
  VIRTUAL_ENV: ${{ github.workspace }}/.venv

jobs:

  molecule:
    runs-on: ubuntu-latest
    matrix:
      scenario: # essential playbooks that we want tested
        - playbook-ibridges
        - playbook-icommands
        - playbook-python-workbench
        - playbook-agisoft
        - playbook-asreview_server
        - playbook-jupyter_rtc
        - playbook-openrefine
        - playbook-openvscode
        - playbook-rstudio_server
        - playbook-robot-server
        - playbook-uu_provisioning
    steps:
      - name: Workaround crun issue on ubuntu
        run: |
          mkdir -p "${HOME}/.local/bin"
          curl -L "https://github.com/containers/crun/releases/download/${CRUN_VER}/crun-${CRUN_VER}-linux-amd64" -o "${HOME}/.local/bin/crun"
          chmod +x "${HOME}/.local/bin/crun"
          crun --version
          mkdir -p "${HOME}/.config/containers"
          cat << EOF > "${HOME}/.config/containers/containers.conf"
          [engine.runtimes]
          crun = [
            "${HOME}/.local/bin/crun",
            "/usr/bin/crun"
          ]
          EOF
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Set up UV and caching
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv venv $VIRTUAL_ENV
          uv pip install -r ${{ env.REQUIREMENTS_FILE }}
          uv run ansible-galaxy install -r ${{ env.ANSIBLE_REQUIREMENTS_FILE }}
          uv run ansible-galaxy install -r requirements.yml
      - name: Molecule tests
        run: |
          uv run molecule -c ${{ env.MOLECULE_CONFIG }} test ${{ matrix.scenario }}
