---
name: Weekly molecule run for playbooks
on:
  schedule:
    - cron: '22 1 * * 1'  # 1:22am on Monday
  workflow_dispatch:

env:
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PW: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REGISTRY: ghcr.io
  ANSIBLE_FORCE_COLOR: '0' # ANSI coloring disables GitHub's ability to mask secrets.
  ANSIBLE_CALLBACK_RESULT_FORMAT: yaml
  MOLECULE_CONFIG: molecule/ext/molecule-src/molecule.yml
  REQUIREMENTS_FILE: molecule/ext/molecule-src/requirements.txt
  ANSIBLE_REQUIREMENTS_FILE: molecule/ext/molecule-src/requirements.yml
  VIRTUAL_ENV: ${{ github.workspace }}/.venv

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: # essential playbooks that we want tested
          - playbook-ibridges
          - playbook-icommands
          - playbook-python-workbench
          - playbook-asreview_server
          - playbook-jupyterhub
          - playbook-jupyter_rtc
          - playbook-matlab
          - playbook-openrefine
          - playbook-openvscodeserver
          - playbook-reverse_proxy
          - playbook-rstudio_server
          - playbook-robot-server
          - playbook-uu_provisioning
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Set up UV and caching
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv venv $VIRTUAL_ENV
          uv pip install -r ${{ env.REQUIREMENTS_FILE }}
          uv run ansible-galaxy install -r ${{ env.ANSIBLE_REQUIREMENTS_FILE }}
          uv run ansible-galaxy install -r requirements.yml
      - name: Molecule tests
        run: |
          scenario_suffix=""
          if [[ -d molecule/${{ matrix.scenario }}/default ]]; then # nested scenario
            scenario_suffix="/*"
          fi
          uv run molecule -c ${{ env.MOLECULE_CONFIG }} test --scenario-name ${{ matrix.scenario }}$scenario_suffix
